# Generated by Django 3.0.3 on 2020-03-03 03:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
                ('admin_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
                ('num_claps', models.IntegerField()),
                ('num_responses', models.IntegerField()),
                ('status', models.CharField(choices=[('dft', 'Draft'), ('pub', 'Published')], default='dft', max_length=3)),
                ('seo_title', models.CharField(max_length=120)),
                ('license', models.CharField(choices=[('opn', 'Open Source'), ('mit', 'MIT License')], default='mit', max_length=3)),
                ('free_link', models.URLField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
