# Generated by Django 3.0.3 on 2020-03-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='Default Title', max_length=120),
            preserve_default=False,
        ),
    ]
