# Generated by Django 3.0.3 on 2020-03-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200303_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='seo_description',
            field=models.TextField(default='Default SEO description'),
            preserve_default=False,
        ),
    ]
