# Generated by Django 3.0.3 on 2020-03-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_admintag_response_responseclap_storyclap'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stories.Story'),
            preserve_default=False,
        ),
    ]
