# Generated by Django 3.0.3 on 2020-03-03 23:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_response_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='admin_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='free_link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='story',
            name='num_claps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='num_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='Untitled', max_length=120),
        ),
    ]
