# Generated by Django 3.0.3 on 2020-03-03 23:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20200303_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='admin_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), size=None),
        ),
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), size=None),
        ),
    ]
