# Generated by Django 3.0.3 on 2020-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20200303_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(default='<div></div>'),
        ),
        migrations.AlterField(
            model_name='story',
            name='free_link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='story',
            name='license',
            field=models.CharField(choices=[('opn', 'Open Source'), ('mit', 'MIT License')], default='mit', max_length=3),
        ),
        migrations.AlterField(
            model_name='story',
            name='seo_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('dft', 'Draft'), ('pub', 'Published')], default='dft', max_length=3),
        ),
    ]
