# Generated by Django 3.0.3 on 2020-03-04 00:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20200304_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='admin_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), default=list, size=None),
        ),
    ]
