# Generated by Django 3.0.3 on 2020-03-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0017_remove_story_free_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='identifier',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
