# Generated by Django 3.0.3 on 2020-03-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0018_story_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='identifier',
            field=models.CharField(default='placeholder', max_length=100),
        ),
    ]
