# Generated by Django 3.0.3 on 2020-03-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_auto_20200304_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='identifier',
        ),
    ]
