# Generated by Django 3.0.3 on 2020-03-04 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0020_remove_story_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentClap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='story',
            old_name='num_responses',
            new_name='num_comments',
        ),
        migrations.RemoveField(
            model_name='storyclap',
            name='count',
        ),
        migrations.RemoveField(
            model_name='storyclap',
            name='updated_at',
        ),
        migrations.RenameModel(
            old_name='Response',
            new_name='Comment',
        ),
        migrations.DeleteModel(
            name='ResponseClap',
        ),
        migrations.AddField(
            model_name='commentclap',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Comment'),
        ),
        migrations.AddField(
            model_name='commentclap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
