# Generated by Django 3.0.3 on 2020-03-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_auto_20200304_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='num_claps',
            field=models.IntegerField(default=0),
        ),
    ]
